# -*- coding: utf-8 -*-
"""NM Doc-Genie

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gf6tZ79wUJ-l3N75GJXFFku2XMm3NA5o
"""

!pip install -U transformers

# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("text-generation", model="ibm-granite/granite-3.3-2b-instruct")
messages = [
    {"role": "user", "content": "Who are you?"},
]
pipe (messages)

#Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
model = AutoModelForCausalLM.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
messages = [
{"role": "user", "content": "Who are you?"},
]
inputs = tokenizer.apply_chat_template(
 messages,
 add_generation_prompt=True,
 tokenize=True,
 return_dict=True,
 return_tensors="pt",
).to(model.device)
outputs = model.generate (**inputs, max_new_tokens=40)
print(tokenizer.decode(outputs[0][inputs ["input_ids"].shape[-1]:]))

!pip install -q gradio transformers torch black autopep8 reportlab requests

!pip install -q gradio transformers torch black autopep8 reportlab requests ast-super-parser

import gradio as gr
from transformers import pipeline

# Load AI model
chatbot = pipeline("text-generation", model="gpt2")

# Chat function
def chat(message, history):
    prompt = message

    response = chatbot(
        prompt,
        max_length=100,
        num_return_sequences=1
    )

    answer = response[0]["generated_text"]

    return answer

# Create interface
demo = gr.ChatInterface(
    fn=chat,
    title="Simple AI Chatbot",
    description="Chat with an AI model powered by Transformers."
)

# Launch web app
demo.launch()